version: '2'
services:
  php7:
    image: kencool107/php7-apache
    links:
      - db
    ports:
      - 9090:80
      - 9999:443
      - 9010:9010
    volumes:
      - ~/workspace:/var/www/html
    restart: always
    networks:
      - ken
  db:
    image: mysql:5.7 # or mariadb
    ports:
      - 3300:3306
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: always
    networks:
      - ken
  phpmyadmin:
      image:
        phpmyadmin/phpmyadmin:latest
      networks:
        - ken
      links:
        - db:pma_db
      restart: always
      ports:
        - "9000:80"
volumes:
  data: {}

networks:
    ken:
        driver:
            bridge
        ipam:
          config:
          - subnet: 172.20.0.0/24
            gateway: 172.20.0.1
