version: '2'
services:
  php7:
    image: kencool107/php7-apache
    links:
      - db
      - redis
    ports:
      - 9090:80
#      - 8080:80
#      - 9999:443
#      - 8080:8080
    volumes:
      - ~/workspace:/var/www/html
      - ./php7-apache/config/apache2/sites-available/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./php7-apache/config/apache2/sites-enabled/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./php7-apache/config/apache2/apache2.conf:/etc/apache2/apache2.conf
      - ./php7-apache/config/apache2/ports.conf:/etc/apache2/ports.conf
      - ./php7-apache/config/php.ini:/usr/local/etc/php/php.ini
      - ./php7-apache/config/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    restart: always
    networks:
      - ken
  db:
    image: mysql:5.7 # or mariadb
    ports:
      - 3300:3306
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: always
    networks:
      - ken
  phpmyadmin:
      image:
        phpmyadmin/phpmyadmin:latest
      networks:
        - ken
      links:
        - db:pma_db
      restart: always
      ports:
        - "9001:80"
  redis:
      image:
        redis:5.0.4
      ports:
        - 6378:6379
      networks:
        - ken
      restart: always
volumes:
  data: {}

networks:
    ken:
        driver:
            bridge
        ipam:
          config:
          - subnet: 172.21.0.0/24
            gateway: 172.21.0.1
